"""add_webhook_fields_to_account

Revision ID: 5cd1450f675e
Revises: 004
Create Date: 2026-04-01 05:27:40.519782
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cd1450f675e'
down_revision: Union[str, None] = '004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('webhook_url', sa.String(length=255), nullable=True, comment='Webhook回调地址'))
    op.add_column('accounts', sa.Column('webhook_secret', sa.String(length=128), nullable=True, comment='Webhook签名密钥'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'webhook_secret')
    op.drop_column('accounts', 'webhook_url')
    # ### end Alembic commands ###
