import type { RouteRecordRaw } from 'vue-router'

/** 管理后台路由 */
export const adminRoutes: RouteRecordRaw[] = [
  {
    path: '/admin/accounts',
    name: 'AdminAccounts',
    component: () => import('@/views/admin/Accounts.vue'),
    meta: { titleKey: 'menu.customers', icon: 'User' },
  },
  {
    path: '/admin/sms-accounts',
    name: 'SmsAccounts',
    component: () => import('@/views/admin/Accounts.vue'),
    props: { defaultBusinessType: 'sms' },
    meta: { titleKey: 'menu.smsAccounts', icon: 'Message' },
  },
  {
    path: '/admin/voice-accounts',
    name: 'VoiceAccounts',
    component: () => import('@/views/admin/Accounts.vue'),
    props: { defaultBusinessType: 'voice' },
    meta: { titleKey: 'menu.voiceAccounts', icon: 'Headset' },
  },
  {
    path: '/admin/data-accounts-list',
    name: 'DataAccountsList',
    component: () => import('@/views/admin/Accounts.vue'),
    props: { defaultBusinessType: 'data' },
    meta: { titleKey: 'menu.dataAccounts', icon: 'DataLine' },
  },
  {
    path: '/admin/staff',
    name: 'AdminStaff',
    component: () => import('@/views/admin/Staff.vue'),
    meta: { titleKey: 'menu.staff', icon: 'UserFilled' },
  },
  {
    path: '/admin/account-templates',
    name: 'AccountTemplates',
    component: () => import('@/views/admin/AccountTemplates.vue'),
    meta: { titleKey: 'menu.accountTemplates', icon: 'Document' },
  },
  {
    path: '/admin/bot/config',
    name: 'BotConfig',
    component: () => import('@/views/bot/Config.vue'),
    meta: { titleKey: 'menu.botConfig', icon: 'Setting' },
  },
  {
    path: '/admin/bot/messages',
    name: 'BotMessages',
    component: () => import('@/views/bot/Messages.vue'),
    meta: { titleKey: 'menu.botMessages', icon: 'ChatDotRound' },
  },
  {
    path: '/admin/bot/invites',
    name: 'BotInvites',
    component: () => import('@/views/bot/Invites.vue'),
    meta: { titleKey: 'menu.botInvites', icon: 'Ticket' },
  },
  {
    path: '/admin/bot/templates',
    name: 'BotTemplates',
    component: () => import('@/views/bot/Templates.vue'),
    meta: { titleKey: 'menu.whitelist', icon: 'Check' },
  },
  {
    path: '/admin/bot/recharge-audit',
    name: 'BotRechargeAudit',
    component: () => import('@/views/bot/RechargeAudit.vue'),
    meta: { titleKey: 'menu.rechargeAudit', icon: 'Money' },
  },
  {
    path: '/admin/bot/batch-audit',
    name: 'BotBatchAudit',
    component: () => import('@/views/bot/BatchAudit.vue'),
    meta: { titleKey: 'menu.batchAudit', icon: 'Stamp' },
  },
  {
    path: '/admin/business-knowledge',
    name: 'BusinessKnowledge',
    component: () => import('@/views/admin/BusinessKnowledge.vue'),
    meta: { titleKey: 'menu.businessKnowledge', icon: 'Document' },
  },
  {
    path: '/admin/profile',
    name: 'AdminProfile',
    component: () => import('@/views/admin/Profile.vue'),
    meta: { titleKey: 'menu.accountManage', icon: 'User' },
  },
  {
    path: '/admin/system/config',
    name: 'SystemConfig',
    component: () => import('@/views/system/Index.vue'),
    meta: { titleKey: 'menu.systemConfig', icon: 'Setting' },
  },
  {
    path: '/admin/pricing',
    redirect: '/channels',
  },
  {
    path: '/admin/suppliers',
    name: 'Suppliers',
    component: () => import('@/views/admin/Suppliers.vue'),
    meta: { titleKey: 'menu.suppliers', icon: 'Shop' },
  },
  {
    path: '/admin/tickets',
    name: 'AdminTickets',
    component: () => import('@/views/admin/Tickets.vue'),
    meta: { titleKey: 'menu.tickets', icon: 'Tickets' },
  },
  {
    path: '/admin/business-accounts',
    name: 'BusinessAccounts',
    component: () => import('@/views/admin/BusinessAccounts.vue'),
    meta: { titleKey: 'menu.businessAccounts', icon: 'Headset' },
  },
  {
    path: '/admin/data/accounts',
    name: 'DataAccounts',
    component: () => import('@/views/admin/data/Accounts.vue'),
    meta: { titleKey: 'menu.dataAccounts', icon: 'User' },
  },
  {
    path: '/admin/data/upload',
    name: 'DataUpload',
    component: () => import('@/views/admin/data/Numbers.vue'),
    meta: { titleKey: 'menu.dataUpload', icon: 'Upload' },
  },
  {
    path: '/admin/data/products',
    name: 'DataProducts',
    component: () => import('@/views/admin/data/Products.vue'),
    meta: { titleKey: 'menu.dataProducts', icon: 'Goods' },
  },
  {
    path: '/admin/data/orders',
    name: 'DataOrders',
    component: () => import('@/views/admin/data/Orders.vue'),
    meta: { titleKey: 'menu.dataOrders', icon: 'ShoppingCart' },
  },
  {
    path: '/admin/data/private-library',
    name: 'AdminPrivateLibrary',
    component: () => import('@/views/admin/data/PrivateLibrary.vue'),
    meta: { titleKey: 'menu.adminCustomerData', icon: 'Box' },
  },
  {
    path: '/admin/data/pricing',
    name: 'DataPricing',
    component: () => import('@/views/admin/data/Pricing.vue'),
    meta: { titleKey: 'menu.dataPricing', icon: 'PriceTag' },
  },
  {
    path: '/admin/reports/business',
    name: 'AdminBusinessReport',
    component: () => import('@/views/admin/BusinessReport.vue'),
    meta: { titleKey: 'menu.businessReport', icon: 'TrendCharts' },
  },
  {
    path: '/admin/water/proxies',
    name: 'WaterProxies',
    component: () => import('@/views/admin/water/ProxyManage.vue'),
    meta: { titleKey: 'menu.waterProxies', icon: 'Connection' },
  },
  {
    path: '/admin/water/tasks',
    name: 'WaterTasks',
    component: () => import('@/views/admin/water/Tasks.vue'),
    meta: { titleKey: 'menu.waterTasks', icon: 'Operation' },
  },
  {
    path: '/admin/water/logs',
    name: 'WaterLogs',
    component: () => import('@/views/admin/water/Logs.vue'),
    meta: { titleKey: 'menu.waterLogs', icon: 'Document' },
  },
  {
    path: '/admin/water/scripts',
    name: 'WaterScripts',
    component: () => import('@/views/admin/water/Scripts.vue'),
    meta: { titleKey: 'menu.waterScripts', icon: 'Edit' },
  },
  {
    path: '/admin/sms/tasks',
    name: 'AdminSmsTasks',
    component: () => import('@/views/admin/sms/Tasks.vue'),
    meta: { titleKey: 'menu.smsTaskManagement', icon: 'Operation' },
  },
  {
    path: '/admin/sms/refund-audit',
    name: 'SmsRefundAudit',
    component: () => import('@/views/admin/sms/RefundAudit.vue'),
    meta: { titleKey: 'menu.smsRefundAudit', icon: 'Money' },
  },
]
